### ISSUE TITLE
package checking compilation flag NOTE

### ISSUE THREAD

**Issue by allenzhuaz** [allenzhuaz/gMCPmini#10]
When running R CMD check under RStudio server, I got the following note:

```
> checking compilation flags used ... NOTE
  Compilation used the following non-portable flag(s):
    ‘-march=x86-64’

```
@nanxstats Would you help take a look whether it is an OS issue

**Comment by nanxstats** [comment]
The GitHub Actions for three Ubuntu checks all look ok. I think we can safely ignore this note as it is related to the system configuration. See https://github.com/r-hub/rhub/issues/264 for details.

At this moment, let's only focus on the GitHub Actions checks as they are relatively more reliable. We can close this issue.
