### ISSUE TITLE
Reduce package dependency 

### ISSUE THREAD

**Issue by elong0527** [allenzhuaz/gMCPmini#5]
Please find possibility to avoid dependency below

   magrittr,
   dplyr,
   tidyr,

**Comment by nanxstats** [comment]
In principle, I agree it's doable. They all came from `R/hgraph.R` and `vignettes/GraphicalMultiplicity.Rmd`.

I'm not sure if I understand the semantic mapping between base R and tidyverse well enough. So, do you care to contribute a patch to move this forward?

https://dplyr.tidyverse.org/articles/base.html
https://tavareshugo.github.io/data_carpentry_extras/base-r_tidyverse_equivalents/base-r_tidyverse_equivalents.html
